# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Shiny3Dprotein.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, Qt
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
import os, sys, re, math, time
from ShinyWeb import ShinyWeb_Form



class winTest(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle('My Browser')
        self.setStyleSheet("background-image: url(./logo/backgroundpage.png)")

    """对QDialog类重写，实现一些功能"""

    def closeEvent(self, event):
        """
        重写closeEvent方法，实现dialog窗体关闭时执行一些代码
        :param event: close()触发的事件
        :return: None
        """
        try:
            with os.popen('netstat -aon|findstr "50330"') as res:
                res = res.read().split('\n')
            result = []
            for line in res:
                temp = [i for i in line.split(' ') if i != '']
                if len(temp) > 4:
                    result.append({'pid': temp[4], 'address': temp[1], 'state': temp[3]})

            if len(result) != 0:
                for task in result:
                    pid = task['pid']
                    os.popen('taskkill -pid %s -f' % (pid))

        except:
            return None  # 设置正常退出


class Shiny3Dprotein_Form(QWidget):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(691, 431)
        Form.setStyleSheet("background-image: url(./logo/backgroundpage.png)")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(60, 150, 271, 151))
        self.textBrowser.setStyleSheet("background-image: url(./logo/white.png)")
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(230, 20, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(19)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(150, 100, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(27)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(430, 160, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(25)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(430, 300, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(25)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(90, 310, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        # button action
        self.pushButton.clicked.connect(self.start)
        self.pushButton_2.clicked.connect(self.open)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Shiny3Dprotein"))
        self.label.setText(_translate("Form", "Shiny3Dprotein"))
        self.label_2.setText(_translate("Form", "Status"))
        self.pushButton.setText(_translate("Form", "Start App"))
        self.pushButton_2.setText(_translate("Form", "Open Web"))
        self.label_3.setText(_translate("Form", "Please close this window before\n"
"starting another Shiny Apps!!!"))


    def start(self):
        self.textBrowser.setText(
            'Start ShinyApp!!!')
        QApplication.processEvents()  # 逐条打印状态

        path = os.path.abspath('.')
        if '\\' in path:
            path = path.strip().split('\\')
            path = '/'.join(path)

        os.popen(path + '/Shiny/R-4.3.2/bin/Rscript ' +
                 path + '/Shiny/ShinyScript/Shiny3Dprotein/Shiny3Dprotein.R')

        time.sleep(3)
        self.textBrowser.setText(
            'ShinyApp has been started!!!')

    def open(self):
        self.winTable = ShinyWeb_Form(port=50330)
        self.winTable.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    # Clustal = QtWidgets.QWidget()
    WT = winTest()
    ui = Shiny3Dprotein_Form()
    ui.setupUi(WT)
    WT.show()
    sys.exit(app.exec_())
