# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JSalignment.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys,os
from PyQt5.QtCore import QUrl
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtWebEngineWidgets import *


class Treevis_Form(QMainWindow):
    def __init__(self):
        super(Treevis_Form, self).__init__()
        self.setWindowTitle('TreeVisualization')  # 窗口标题
        self.setGeometry(5, 30, 700, 600)  # 窗口的大小和位置设置
        self.browser = QWebEngineView()
        path = os.path.abspath('.')
        if '\\' in path:
            path = path.strip().split('\\')
            path = '/'.join(path)
            print(path)
        self.browser.load(QUrl(path + '/html/treevis/phylogeny-tree.html'))
        self.setCentralWidget(self.browser)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    win = Treevis_Form()
    win.show()
    app.exit(app.exec_())
