# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProtVista.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys,os,shutil
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5 import QtCore, QtGui, QtWidgets, Qt
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtWebEngineWidgets import QWebEngineView
from ProtVistaWeb import ProtVistaWeb_Form


class winTest(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setWindowTitle('My Browser')

    """对QDialog类重写，实现一些功能"""

    def closeEvent(self, event):
        """
        重写closeEvent方法，实现dialog窗体关闭时执行一些代码
        :param event: close()触发的事件
        :return: None
        """
        try:
            if os.path.exists(os.path.dirname(content_final) + '/external_P05067.json') == True:
                print(content_final)
                os.remove(os.path.dirname(content_final) + '/external_P05067.json')
            else:
                return None  # 设置正常退出
        except:
            return None  # 设置正常退出

class Protvista_Form(QWidget):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(551, 407)
        Form.setWindowIcon(QIcon("./logo/logo.ico"))
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout.addWidget(self.textBrowser_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(19)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        # action
        self.pushButton.clicked.connect(self.web_open)
        self.pushButton_2.clicked.connect(self.read_file1)

        ## default
        self.textBrowser_2.setPlaceholderText("D:/input/ex.json")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "ProtVista"))
        self.label.setText(_translate("Form", "ProtVista"))
        self.pushButton_2.setText(_translate("Form", "Choose"))
        self.label_2.setText(_translate("Form", "Input JSON file"))
        self.pushButton.setText(_translate("Form", "Run"))

    def read_file1(self):
        openfile_name = QtWidgets.QFileDialog.getOpenFileName(self, 'choose file', '')[0]
        print(openfile_name)
        self.textBrowser_2.setText(openfile_name)


    def web_open(self):
        # 绑定按钮点击事件，发射信号
        content = self.textBrowser_2.toPlainText()
        content = content.strip()
        content_file = os.path.basename(content)

        bool_1 = content_file.endswith(".json")
        bool_2 = content_file.endswith(".JSON")
        bool_3 = content_file.endswith(".Json")
        print(bool_1 or bool_2 or bool_3 == True)

        if bool_1 or bool_2 or bool_3 == True:
            path_1 = os.path.abspath('.')
            path_1 = path_1.strip().split('\\')
            path = '/'.join(path_1) + "/html/protvista/"

            shutil.copy(content, path)
            global content_final
            if os.path.exists(path + 'external_P05067.json'):
                os.remove(path + 'external_P05067.json')
                os.rename(path + content_file, path + 'external_P05067.json')
                content_final = path + 'external_P05067.json'
            else:
                os.rename(path + content_file, path + 'external_P05067.json')
                content_final = path + 'external_P05067.json'

            print(content_final)
            if content_final == '':
                w = QWidget()
                QMessageBox.critical(w, "error",
                                     "Please add correct path!")
            else:
                self.winTable = ProtVistaWeb_Form(content_final)
                self.winTable.show()
        else:
            QMessageBox.critical(self, "error", "Please check format(suffix: json or JSON)!")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WT = QtWidgets.QWidget()
    WT = winTest()
    ui = Protvista_Form()
    ui.setupUi(WT)
    WT.show()
    sys.exit(app.exec_())
